title: Zonda Github io
author: Zonda Yang
description: Zonda Github io
lang: en

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post

icons:
  github: "https://github.com/zondaTW"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
