title: Zonda Github io
author: Zonda Yang
description: Zonda Github io

# Page settings
permalink: /:year/:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

icons:
  github: "https://github.com/zondaTW"

paginate: 12                  # number of articles per page

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
